#!/usr/bin/env bash
# Bash script that transfers a file from client to server

# Initialize variable
path_to_file=$1
server_ip=$2
username=$3
path_to_key=$4

if [[ $# -lt 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

scp -i "$path_to_key" "$path_to_file" "$username"@"$server_ip":'~/'
