#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# configure firewall to allow access to the service
# nginx registers itself as a service with 'ufw', our firewall, upon installation
sudo ufw allow 'Nginx HTTP'

# edit the file
echo "Hello World!" >/var/www/html/index.html
# reload nginx server
sudo service nginx reload
