#!/usr/bin/env bash
# Install HAProxy load balancer

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.9

apt-get update
apt-get -y install haproxy=2.9.\*

balancer_command="\
\\\nfrontend lb-01\n\
        bind :80\n\
        mode http\n\
        default_backend web_servers\n\n\
backend web_servers\n\
        balance roundrobin\n\
        server 271204-web-01 35.153.194.40:80 check\n\
        server 271204-web-02 34.229.72.29:80 check
"

sed -i "35a $balancer_command" /etc/haproxy/haproxy.cfg

# enable the service
systemctl enable haproxy.service
systemctl restart haproxy.service
