#!/usr/bin/env bash
# Install HAProxy load balancer

apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.9

sudo apt-get install haproxy=2.9.\*

# enable the service
sudo systemctl enable haproxy.service
sudo systemctl start haproxy.service

CONFIG="\\nfrontend lb-01\n\
    \tbind *:80\n\
    \tmode http\n\n\
    backend web-01\n\
    \tbalance roundrobin\n\
    \tserver web1 35.153.194.40:80 check\n\
    backend web-02\n\
    \tbalance roundrobin\n\
    \tserver web2 34.229.72.29:80 check\n
"

if [[ -e /etc/haproxy/haproxy.cfg ]]; then
	sudo sed -i "34i $CONFIG" /etc/haproxy/haproxy.cfg
fi
