#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <mysql_root_password>"
    exit 1
fi

MYSQL_PASSWORD=$1

if ! mysqldump --user=root --password="$MYSQL_PASSWORD" --all-databases >backup.sql; then
    echo "Failed to create backup"
    exit 1
fi

DATE=$(date +%d-%m-%Y)

if ! tar -czf "$DATE".tar.gz backup.sql; then
    echo "Compression failed"
    exit 1
fi
