#!/usr/bin/env bash
# Install apache and get it to return the string "Holberton School"

sudo apt update
sudo apt install apache2
sudo service apache2 start
echo "Hello Holberton" > /var/www/html/index.html
