#!/usr/bin/env bash
# Install apache and get it to return the string "Holberton School"

apt update
apt install apache2
cp /var/www/html/index.html{,.bak}
echo "Hello Holberton" > /var/www/html/index.html
