#!/usr/bin/env bash
# Install nginx and configure to run as previledge user not root user

NGINX_CONFIG="/etc/nginx/nginx.conf"
sudo chmod 777 "$NGINX_CONFIG"
sudo pkill apache2

# update Nginx configuration
if [ -f "$NGINX_CONFIG" ]; then
	sudo sed -i 's/^user .*/user nginx;/g' "$NGINX_CONFIG"
	sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
	sudo sed -i 's/listen \[::\]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default
else
	echo "Nginx cofiguration not found!"
	exit 1
fi

sudo -u nginx service nginx start
