#!/usr/bin/env bash
# Install nginx and configure to run as previledge user not root user
sudo chmod 777 "/etc/nginx/nginx.conf"
sudo pkill apache2
sudo sed -i 's/^user .*/user nginx;/g' "/etc/nginx/nginx.conf"
sudo sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
